# Generated by Django 5.0.6 on 2024-05-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('toy_name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='toy_name')),
                ('toy_model', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='toy_model')),
                ('toy_price', models.FloatField(verbose_name='toy_price')),
                ('toy_description', models.CharField(max_length=2000, verbose_name='toy_description')),
            ],
            options={
                'db_table': 'toys',
            },
        ),
    ]
