# Generated by Django 5.0.6 on 2024-05-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='toy_model',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='toy_model'),
        ),
    ]
